### ISSUE TITLE
Validación de IPs

### ISSUE THREAD

**Issue by NadiaFinzi** [mumuki/mumuki-text-runner#15]
Debería soportar una forma de validar IPs

**Comment by Charlyzzz** [comment]
Podés validar IPs utilizando expresiones regulares. Podés probar [acá](https://regexr.com/).

**Comment by flbulgarelli** [comment]
Ah, no me acordaba que este runner ya soportaba expresiones regulares. Quizás se podría probar así: 

```
- name: 'testIps'
  postconditions:
    match: [0-9]+\.[0-9]+\.[0-9]+\.[0-9]+
```

**Comment by Charlyzzz** [comment]
También podrías usar algo como `((\d{1,3})\.){3}\d{1,3}`

**Comment by flbulgarelli** [comment]
Soluciones posibles: 

Opción 1 (no tan correcta, pero entendible)

```
- name: la ip tiene el formato correcto
  postconditions:
    match: /[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}/
```

Opción 2 (aparentemente más correcta, pero también más ofuscada). Cortesía de https://gist.github.com/marvin/1017389/a1027445db37749ecca57c299643182f0759e485: 


```
- name: la ip tiene el formato correcto
  postconditions:
    match: /^((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$/i
```

**Comment by flbulgarelli** [comment]
@NadiaFinzi probá estas opciones y cerrá el issue si todo está bien.

**Comment by flbulgarelli** [comment]
PD: Necesitamos resolver https://github.com/mumuki/mumuki-text-runner/issues/17 antes

**Comment by julian-berbel** [comment]
Para referencia futura, las expresiones regulares en el YAML se tienen que escribir como:
una-regex: !ruby/regexp '/texto para matchear/'

y a la regex de la ip no tan correcta habría que agregarle ^ al principio y $ al final, sino algo como '1234.567.890.1234' matchearía
